package Views;

import Facade.FachadaLogin;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mario
 */
public class InicioCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazClienteTest
     */
    public InicioCliente() {
        initComponents();
        URL pathIcon = this.getClass().getClassLoader().getResource("images/logo.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(pathIcon);
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnCarro = new javax.swing.JLabel();
        btnInicio = new javax.swing.JLabel();
        btnProducto = new javax.swing.JLabel();
        btnMontar = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        btnCompras = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fotoInicio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        panelElegirProducto = new javax.swing.JPanel();
        infoPanelAnadir1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        panelArticulo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        raton = new javax.swing.JLabel();
        placaBase = new javax.swing.JLabel();
        cpu = new javax.swing.JLabel();
        grafica = new javax.swing.JLabel();
        caja = new javax.swing.JLabel();
        monitor = new javax.swing.JLabel();
        teclado = new javax.swing.JLabel();
        disco = new javax.swing.JLabel();
        cam = new javax.swing.JLabel();
        fuente = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        pctorre = new javax.swing.JLabel();
        portatil = new javax.swing.JLabel();
        panelCarro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedidos = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        precioCarro = new javax.swing.JLabel();
        btnRealizaPedidoCarro = new javax.swing.JButton();
        eliminarArticulo = new javax.swing.JButton();
        eliminaTodoCarro = new javax.swing.JButton();
        panelMonta = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        cajaBox = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        precioTotalPc = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        cpuBox = new javax.swing.JComboBox<>();
        placaBox = new javax.swing.JComboBox<>();
        ramBox = new javax.swing.JComboBox<>();
        graficaBox = new javax.swing.JComboBox<>();
        discoBox = new javax.swing.JComboBox<>();
        fuenteBox = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        ratonBox = new javax.swing.JComboBox<>();
        tecladoBox = new javax.swing.JComboBox<>();
        camBox = new javax.swing.JComboBox<>();
        montaYcompra = new javax.swing.JButton();
        montaYguarda = new javax.swing.JButton();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        panelProducto = new javax.swing.JPanel();
        puntuacion1 = new javax.swing.JButton();
        confirmaPuntuacion = new javax.swing.JLabel();
        productoSeleccionado = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        datoModelo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datoStock = new javax.swing.JLabel();
        nombreAtributo1 = new javax.swing.JLabel();
        atrParticular1 = new javax.swing.JLabel();
        nombreAtributo2 = new javax.swing.JLabel();
        atrParticular2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        codigo_ref = new javax.swing.JLabel();
        nombreAtributo3 = new javax.swing.JLabel();
        atrParticular3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnComprarProducto = new javax.swing.JButton();
        insertarCesta = new javax.swing.JButton();
        descripcion1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextPane();
        imgProducto = new javax.swing.JLabel();
        puntuacion2 = new javax.swing.JButton();
        puntuacion3 = new javax.swing.JButton();
        puntuacion4 = new javax.swing.JButton();
        puntuacion5 = new javax.swing.JButton();
        datoMediaEvaluacion = new javax.swing.JLabel();
        panelPerfil = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        nuevoEmail = new javax.swing.JTextField();
        nombrePerfil = new javax.swing.JLabel();
        apellidoPerfil = new javax.swing.JLabel();
        datoEmail = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        nuevaPass = new javax.swing.JPasswordField();
        repitePass = new javax.swing.JPasswordField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btnCambiaEmail = new javax.swing.JButton();
        btnCambiaContra = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        datoTarjeta = new javax.swing.JTextField();
        datoTelefono = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        btnCambiaAtributos = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        datoDireccion = new javax.swing.JTextField();
        panelCompras = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCompras = new javax.swing.JList<>();
        panelInfoPedido = new javax.swing.JPanel();
        infoPanelAnadir3 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaInfoPedido = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        nPedidoInfo = new javax.swing.JLabel();
        correoInfoPedido = new javax.swing.JLabel();
        fechaPedidoInf = new javax.swing.JLabel();
        btnEliminarPedido = new javax.swing.JButton();
        btnRecepcionPedido = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        labelDeshacer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 10));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 50));

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ElReyDelPc");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 80));

        nombreCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        nombreCliente.setText("Name1");
        jPanel2.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, 40));

        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Online");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 70, 20));

        textoBusqueda.setBackground(new java.awt.Color(51, 51, 51));
        textoBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        textoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoBusqueda.setBorder(null);
        textoBusqueda.setCaretColor(new java.awt.Color(255, 255, 255));
        textoBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(textoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 40));

        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 40));

        btnCarro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCarro.setForeground(new java.awt.Color(255, 255, 255));
        btnCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Carrito.png"))); // NOI18N
        btnCarro.setText("Carrito");
        btnCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 230, 60));

        btnInicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 60));

        btnProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        btnProducto.setText("Productos");
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 70));

        btnMontar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMontar.setForeground(new java.awt.Color(255, 255, 255));
        btnMontar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustes.png"))); // NOI18N
        btnMontar.setText("Monta tu PC");
        btnMontar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnMontar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 230, 70));

        btnPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        btnPerfil.setText("Gestiona tu perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, 60));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 240, -1));

        jSeparator40.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 570, 250, -1));

        btnCompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        btnCompras.setText(" Ver compras");
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 230, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 700));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSesion.png"))); // NOI18N
        btnCerrar.setText("Cerrar sesion");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 160, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 960, 80));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicio.setBackground(new java.awt.Color(51, 51, 51));
        panelInicio.setPreferredSize(new java.awt.Dimension(960, 620));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Conocenos ");
        panelInicio.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pagina de inicio");
        panelInicio.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelInicio.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        fotoInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fotopc.png"))); // NOI18N
        panelInicio.add(fotoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 340, 260));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texto.png"))); // NOI18N
        panelInicio.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 850, 300));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        panelInicio.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelInicio.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        panelInicio.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        jPanel6.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        panelElegirProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelElegirProducto.setPreferredSize(new java.awt.Dimension(960, 620));
        panelElegirProducto.setVisible(false);
        panelElegirProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir1.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Catálogo de productos");
        infoPanelAnadir1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));
        infoPanelAnadir1.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator36.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir1.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 71));

        jLabel55.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("Elija el producto a editar");
        infoPanelAnadir1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelElegirProducto.add(infoPanelAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        listaProductos.setBackground(new java.awt.Color(51, 51, 51));
        listaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaProductos.setForeground(new java.awt.Color(255, 255, 255));
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(listaProductos);

        panelElegirProducto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 800, 450));

        jPanel6.add(panelElegirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelArticulo.setBackground(new java.awt.Color(51, 51, 51));
        panelArticulo.setPreferredSize(new java.awt.Dimension(960, 620));
        panelArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelArticulo.setVisible(false);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Seleccione producto");
        panelArticulo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Productos");
        panelArticulo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelArticulo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        panelArticulo.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelArticulo.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        panelArticulo.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        raton.setForeground(new java.awt.Color(255, 255, 255));
        raton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        raton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mouse_46934.png"))); // NOI18N
        raton.setText("Raton");
        raton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        raton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(raton, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 330, 130, 40));

        placaBase.setForeground(new java.awt.Color(255, 255, 255));
        placaBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placaBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placa.png"))); // NOI18N
        placaBase.setText("Placa base");
        placaBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        placaBase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(placaBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, 40));

        cpu.setForeground(new java.awt.Color(255, 255, 255));
        cpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cpu_78933.png"))); // NOI18N
        cpu.setText("CPU");
        cpu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cpu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 200, 130, 40));

        grafica.setForeground(new java.awt.Color(255, 255, 255));
        grafica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nvidia_23133.png"))); // NOI18N
        grafica.setText("Grafica");
        grafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        grafica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 200, 130, 40));

        caja.setForeground(new java.awt.Color(255, 255, 255));
        caja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/torre.png"))); // NOI18N
        caja.setText("Caja");
        caja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 130, 40));

        monitor.setForeground(new java.awt.Color(255, 255, 255));
        monitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monitor.png"))); // NOI18N
        monitor.setText("Monitor");
        monitor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monitor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, 40));

        teclado.setForeground(new java.awt.Color(255, 255, 255));
        teclado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keyboard.png"))); // NOI18N
        teclado.setText("Teclado");
        teclado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        teclado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 330, 130, 40));

        disco.setForeground(new java.awt.Color(255, 255, 255));
        disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hd.png"))); // NOI18N
        disco.setText("Discos");
        disco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        disco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 130, 40));

        cam.setForeground(new java.awt.Color(255, 255, 255));
        cam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cam.png"))); // NOI18N
        cam.setText("WebCam");
        cam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 130, 40));

        fuente.setForeground(new java.awt.Color(255, 255, 255));
        fuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fa.png"))); // NOI18N
        fuente.setText("Fuente alimentacion");
        fuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(fuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 160, 40));

        ram.setForeground(new java.awt.Color(255, 255, 255));
        ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ram.png"))); // NOI18N
        ram.setText("Memoria RAM");
        ram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 460, 130, 40));

        pctorre.setForeground(new java.awt.Color(255, 255, 255));
        pctorre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pctorre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        pctorre.setText("PC Torre");
        pctorre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pctorre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(pctorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 460, 130, 40));

        portatil.setForeground(new java.awt.Color(255, 255, 255));
        portatil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portatil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portatil.png"))); // NOI18N
        portatil.setText("Portatil");
        portatil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        portatil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArticulo.add(portatil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 130, 40));

        jPanel6.add(panelArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelCarro.setBackground(new java.awt.Color(51, 51, 51));
        panelCarro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPedidos.setBackground(new java.awt.Color(51, 51, 51));
        listaPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaPedidos.setForeground(new java.awt.Color(255, 255, 255));
        listaPedidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(listaPedidos);

        panelCarro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 670, 370));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tus articulos guardados");
        panelCarro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Carrito");
        panelCarro.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelCarro.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jSeparator32.setForeground(new java.awt.Color(255, 255, 255));
        panelCarro.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator33.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelCarro.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator34.setForeground(new java.awt.Color(255, 255, 255));
        panelCarro.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio Total:");
        panelCarro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 150, 40));

        precioCarro.setForeground(new java.awt.Color(255, 255, 255));
        precioCarro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioCarro.setText("jLabel5");
        panelCarro.add(precioCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 110, 30));

        btnRealizaPedidoCarro.setText("Realizar pedido");
        btnRealizaPedidoCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizaPedidoCarro.setFocusPainted(false);
        panelCarro.add(btnRealizaPedidoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 180, -1));

        eliminarArticulo.setText("Eliminar");
        eliminarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarArticulo.setFocusPainted(false);
        panelCarro.add(eliminarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 180, 40));

        eliminaTodoCarro.setText("Eliminar todo");
        eliminaTodoCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminaTodoCarro.setFocusPainted(false);
        panelCarro.add(eliminaTodoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 180, 40));

        panelCarro.setVisible(false);

        jPanel6.add(panelCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelMonta.setBackground(new java.awt.Color(51, 51, 51));
        panelMonta.setMinimumSize(new java.awt.Dimension(960, 620));
        panelMonta.setPreferredSize(new java.awt.Dimension(960, 620));
        panelMonta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMonta.setVisible(false);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Montaje");
        panelMonta.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Monta tu PC");
        panelMonta.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelMonta.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        panelMonta.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelMonta.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        panelMonta.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        panelMonta.add(cajaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 190, -1));

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Precio total:");
        panelMonta.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 110, 40));

        precioTotalPc.setForeground(new java.awt.Color(255, 255, 255));
        precioTotalPc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioTotalPc.setText("0.0 €");
        panelMonta.add(precioTotalPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 236, 120, 20));

        jLabel56.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Seleccione los productos para el montaje");
        panelMonta.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 30));

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Caja");
        panelMonta.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 535, 70, 30));

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("CPU");
        panelMonta.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 30));

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Placa base");
        panelMonta.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 30));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("RAM");
        panelMonta.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, 70, 30));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Grafica");
        panelMonta.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 372, 70, 30));

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Disco duro");
        panelMonta.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 425, 70, 30));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Fuente");
        panelMonta.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 482, 70, 30));

        panelMonta.add(cpuBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, -1));

        panelMonta.add(placaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 265, 190, -1));

        panelMonta.add(ramBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, -1));

        panelMonta.add(graficaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 375, 190, -1));

        panelMonta.add(discoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 190, -1));

        panelMonta.add(fuenteBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 485, 190, -1));

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Extras:");
        panelMonta.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 70, 40));

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Raton");
        panelMonta.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 60, 30));

        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Teclado");
        panelMonta.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 372, 60, 30));

        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("WebCam");
        panelMonta.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 425, 70, 30));

        panelMonta.add(ratonBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 180, -1));

        panelMonta.add(tecladoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 375, 180, -1));

        panelMonta.add(camBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 180, -1));

        montaYcompra.setText("Montar y comprar");
        montaYcompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        montaYcompra.setFocusPainted(false);
        panelMonta.add(montaYcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 150, -1));

        montaYguarda.setText("Guarda productos");
        montaYguarda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        montaYguarda.setFocusPainted(false);
        panelMonta.add(montaYguarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 150, 30));

        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelMonta.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 305, 40, 168));
        panelMonta.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 350, 10));
        panelMonta.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 350, 10));
        panelMonta.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 10));
        panelMonta.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, 660, 10));
        panelMonta.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 660, 10));
        panelMonta.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 415, 660, 10));
        panelMonta.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 660, 10));
        panelMonta.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 525, 350, 10));

        jSeparator31.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelMonta.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 380));

        jPanel6.add(panelMonta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntuacion1.setBackground(new java.awt.Color(51, 51, 51));
        puntuacion1.setForeground(new java.awt.Color(51, 51, 51));
        puntuacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starVacia.png"))); // NOI18N
        puntuacion1.setBorder(null);
        puntuacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puntuacion1.setEnabled(false);
        puntuacion1.setFocusPainted(false);
        puntuacion1.setOpaque(false);
        panelProducto.add(puntuacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 50, 40));

        confirmaPuntuacion.setForeground(new java.awt.Color(255, 255, 255));
        confirmaPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmaPuntuacion.setText("¡ Puntuacion enviada !");
        panelProducto.add(confirmaPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 290, -1));

        productoSeleccionado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        productoSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        productoSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productoSeleccionado.setText("productoSeleccionado");
        panelProducto.add(productoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Productos");
        panelProducto.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelProducto.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        panelProducto.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelProducto.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        panelProducto.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Caracteristicas:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modelo");

        datoModelo.setForeground(new java.awt.Color(204, 204, 204));
        datoModelo.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stock");

        datoStock.setForeground(new java.awt.Color(204, 204, 204));
        datoStock.setText("jLabel9");

        nombreAtributo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombreAtributo1.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtributo1.setText("AtributoParticular*");
        nombreAtributo1.setVisible(false);

        atrParticular1.setForeground(new java.awt.Color(204, 204, 204));
        atrParticular1.setText("jLabel9");
        atrParticular1.setVisible(false);

        nombreAtributo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombreAtributo2.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtributo2.setText("AtributoParticular*");
        nombreAtributo2.setVisible(false);

        atrParticular2.setForeground(new java.awt.Color(204, 204, 204));
        atrParticular2.setText("jLabel11");
        atrParticular2.setVisible(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio");

        precio.setForeground(new java.awt.Color(204, 204, 204));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precio.setText("jLabel10");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Codigo referencia");

        codigo_ref.setForeground(new java.awt.Color(204, 204, 204));
        codigo_ref.setText("jLabel14");

        nombreAtributo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombreAtributo3.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtributo3.setText("AtributoParticular*");
        nombreAtributo3.setVisible(false);

        atrParticular3.setForeground(new java.awt.Color(204, 204, 204));
        atrParticular3.setText("jLabel18");
        atrParticular3.setVisible(false);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Descripcion");

        btnComprarProducto.setText("Comprar");
        btnComprarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprarProducto.setFocusPainted(false);

        insertarCesta.setText("Cesta");
        insertarCesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarCesta.setFocusPainted(false);

        descripcion1.setBackground(new java.awt.Color(51, 51, 51));
        descripcion1.setForeground(new java.awt.Color(51, 51, 51));
        descripcion1.setOpaque(false);

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(51, 51, 51));
        descripcion.setForeground(new java.awt.Color(51, 51, 51));
        descripcion.setCaretColor(new java.awt.Color(51, 51, 51));
        descripcion.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        descripcion.setOpaque(false);
        descripcion.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        descripcion1.setViewportView(descripcion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(datoModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(atrParticular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(atrParticular2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreAtributo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreAtributo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(codigo_ref, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(atrParticular3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(datoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombreAtributo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(btnComprarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(insertarCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(descripcion1)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datoModelo)
                    .addComponent(codigo_ref))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datoStock)
                    .addComponent(atrParticular1))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAtributo3)
                    .addComponent(nombreAtributo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrParticular3)
                    .addComponent(atrParticular2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnComprarProducto)
                        .addComponent(insertarCesta)))
                .addGap(31, 31, 31))
        );

        panelProducto.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 490));

        imgProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgProducto.setText("VISTA PREVIA");
        panelProducto.add(imgProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 310));

        puntuacion2.setBackground(new java.awt.Color(51, 51, 51));
        puntuacion2.setForeground(new java.awt.Color(51, 51, 51));
        puntuacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starVacia.png"))); // NOI18N
        puntuacion2.setBorder(null);
        puntuacion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puntuacion2.setEnabled(false);
        puntuacion2.setFocusPainted(false);
        puntuacion2.setOpaque(false);
        panelProducto.add(puntuacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 50, 40));

        puntuacion3.setBackground(new java.awt.Color(51, 51, 51));
        puntuacion3.setForeground(new java.awt.Color(51, 51, 51));
        puntuacion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starVacia.png"))); // NOI18N
        puntuacion3.setBorder(null);
        puntuacion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puntuacion3.setEnabled(false);
        puntuacion3.setFocusPainted(false);
        puntuacion3.setOpaque(false);
        panelProducto.add(puntuacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 50, 40));

        puntuacion4.setBackground(new java.awt.Color(51, 51, 51));
        puntuacion4.setForeground(new java.awt.Color(51, 51, 51));
        puntuacion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starVacia.png"))); // NOI18N
        puntuacion4.setBorder(null);
        puntuacion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puntuacion4.setEnabled(false);
        puntuacion4.setFocusPainted(false);
        puntuacion4.setOpaque(false);
        panelProducto.add(puntuacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 50, 40));

        puntuacion5.setBackground(new java.awt.Color(51, 51, 51));
        puntuacion5.setForeground(new java.awt.Color(51, 51, 51));
        puntuacion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starVacia.png"))); // NOI18N
        puntuacion5.setBorder(null);
        puntuacion5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puntuacion5.setEnabled(false);
        puntuacion5.setFocusPainted(false);
        puntuacion5.setOpaque(false);
        panelProducto.add(puntuacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 50, 40));

        datoMediaEvaluacion.setForeground(new java.awt.Color(255, 255, 255));
        datoMediaEvaluacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datoMediaEvaluacion.setText("label5");
        datoMediaEvaluacion.setToolTipText("");
        panelProducto.add(datoMediaEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 505, 290, -1));

        panelProducto.setVisible(false);

        jPanel6.add(panelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelPerfil.setBackground(new java.awt.Color(51, 51, 51));
        panelPerfil.setForeground(new java.awt.Color(255, 255, 255));
        panelPerfil.setPreferredSize(new java.awt.Dimension(960, 620));
        panelPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelPerfil.setVisible(false);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Perfil");
        panelPerfil.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Gestiona tu perfil");
        panelPerfil.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelPerfil.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        panelPerfil.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelPerfil.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        panelPerfil.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email :");
        panelPerfil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 60, 30));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nombre");
        panelPerfil.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, 30));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Apellido");
        panelPerfil.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 30));

        nuevoEmail.setText("example@gmail.com");
        panelPerfil.add(nuevoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 200, 30));

        nombrePerfil.setForeground(new java.awt.Color(255, 255, 255));
        nombrePerfil.setText("jLabel42");
        panelPerfil.add(nombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        apellidoPerfil.setForeground(new java.awt.Color(255, 255, 255));
        apellidoPerfil.setText("jLabel43");
        panelPerfil.add(apellidoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        datoEmail.setForeground(new java.awt.Color(255, 255, 255));
        datoEmail.setText("jLabel44");
        panelPerfil.add(datoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Cambiar contraseña: ");
        panelPerfil.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 190, 30));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Cambiar correo");
        panelPerfil.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 30));

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("DATOS PERSONALES");
        panelPerfil.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 40));
        panelPerfil.add(nuevaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 190, -1));
        panelPerfil.add(repitePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 190, -1));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Repitela");
        panelPerfil.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 110, 20));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Nueva cotraseña");
        panelPerfil.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 110, 20));

        btnCambiaEmail.setText("Cambiar");
        btnCambiaEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiaEmail.setFocusPainted(false);
        panelPerfil.add(btnCambiaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 100, 30));

        btnCambiaContra.setText("Cambiar");
        btnCambiaContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiaContra.setFocusPainted(false);
        panelPerfil.add(btnCambiaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 90, -1));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Tarjeta");
        panelPerfil.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 100, 30));

        datoTarjeta.setText("jTextField3");
        panelPerfil.add(datoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 270, 30));

        datoTelefono.setText("jTextField4");
        panelPerfil.add(datoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 120, 30));

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Telefono");
        panelPerfil.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 140, 30));

        btnCambiaAtributos.setText("Guardar");
        btnCambiaAtributos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiaAtributos.setFocusPainted(false);
        panelPerfil.add(btnCambiaAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 180, 40));

        jLabel52.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Direccion");
        panelPerfil.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 100, 30));

        datoDireccion.setText("Direcion1");
        panelPerfil.add(datoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 270, 30));

        jPanel6.add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        panelCompras.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Tu tienda de tecnología online líder por precio, calidad y servicio");
        panelCompras.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 520, 60));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Mis pedidos");
        panelCompras.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 60));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Resumen pedidos");
        panelCompras.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jSeparator42.setForeground(new java.awt.Color(255, 255, 255));
        panelCompras.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 30));

        jSeparator41.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelCompras.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 130));

        jSeparator39.setForeground(new java.awt.Color(255, 255, 255));
        panelCompras.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 960, 20));

        listaCompras.setBackground(new java.awt.Color(51, 51, 51));
        listaCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaCompras.setForeground(new java.awt.Color(255, 255, 255));
        listaCompras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(listaCompras);

        panelCompras.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 820, 380));

        panelCompras.setVisible(false);

        jPanel6.add(panelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        panelInfoPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelInfoPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInfoPedido.setPreferredSize(new java.awt.Dimension(960, 620));
        panelInfoPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir3.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Resumen pedido");
        infoPanelAnadir3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));
        infoPanelAnadir3.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator38.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir3.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 71));

        jLabel69.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("Información acerca de un pedido");
        infoPanelAnadir3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelInfoPedido.add(infoPanelAnadir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        jScrollPane5.setToolTipText("");

        listaInfoPedido.setBackground(new java.awt.Color(51, 51, 51));
        listaInfoPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaInfoPedido.setForeground(new java.awt.Color(255, 255, 255));
        listaInfoPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaInfoPedido.setToolTipText("");
        jScrollPane5.setViewportView(listaInfoPedido);

        panelInfoPedido.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 800, 330));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nº PEDIDO - ");

        nPedidoInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nPedidoInfo.setForeground(new java.awt.Color(255, 255, 255));
        nPedidoInfo.setText("ID PEDIDO");

        correoInfoPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        correoInfoPedido.setForeground(new java.awt.Color(255, 255, 255));
        correoInfoPedido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        correoInfoPedido.setText("email");

        fechaPedidoInf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fechaPedidoInf.setForeground(new java.awt.Color(255, 255, 255));
        fechaPedidoInf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaPedidoInf.setText("jLabel5");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nPedidoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaPedidoInf, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(correoInfoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(nPedidoInfo)
                    .addComponent(correoInfoPedido)
                    .addComponent(fechaPedidoInf))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelInfoPedido.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 70));

        btnEliminarPedido.setText("Eliminar pedido");
        btnEliminarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInfoPedido.add(btnEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 510, 150, -1));

        btnRecepcionPedido.setText("Confirmar recepción");
        btnRecepcionPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecepcionPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionPedidoActionPerformed(evt);
            }
        });
        panelInfoPedido.add(btnRecepcionPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 550, 190, -1));

        btnDeshacer.setText("Deshacer");
        btnDeshacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeshacer.setVisible(false);
        panelInfoPedido.add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 110, -1));

        labelDeshacer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        labelDeshacer.setText("Pedido eliminado");
        labelDeshacer.setVisible(false);
        panelInfoPedido.add(labelDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 130, -1));

        panelInfoPedido.setVisible(false);

        jPanel6.add(panelInfoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Login loginVista = new Login();
        FachadaLogin login = new FachadaLogin(loginVista);

        this.setVisible(false);
        login.iniciar();
        loginVista.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnRecepcionPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecepcionPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel apellidoPerfil;
    public javax.swing.JLabel atrParticular1;
    public javax.swing.JLabel atrParticular2;
    public javax.swing.JLabel atrParticular3;
    public javax.swing.JLabel btnBuscar;
    public javax.swing.JButton btnCambiaAtributos;
    public javax.swing.JButton btnCambiaContra;
    public javax.swing.JButton btnCambiaEmail;
    public javax.swing.JLabel btnCarro;
    public javax.swing.JLabel btnCerrar;
    public javax.swing.JButton btnComprarProducto;
    public javax.swing.JLabel btnCompras;
    public javax.swing.JButton btnDeshacer;
    public javax.swing.JButton btnEliminarPedido;
    public javax.swing.JLabel btnInicio;
    public javax.swing.JLabel btnMontar;
    public javax.swing.JLabel btnPerfil;
    public javax.swing.JLabel btnProducto;
    public javax.swing.JButton btnRealizaPedidoCarro;
    public javax.swing.JButton btnRecepcionPedido;
    public javax.swing.JLabel caja;
    public javax.swing.JComboBox<String> cajaBox;
    public javax.swing.JLabel cam;
    public javax.swing.JComboBox<String> camBox;
    public javax.swing.JLabel codigo_ref;
    public javax.swing.JLabel confirmaPuntuacion;
    public javax.swing.JLabel correoInfoPedido;
    public javax.swing.JLabel cpu;
    public javax.swing.JComboBox<String> cpuBox;
    public javax.swing.JTextField datoDireccion;
    public javax.swing.JLabel datoEmail;
    public javax.swing.JLabel datoMediaEvaluacion;
    public javax.swing.JLabel datoModelo;
    public javax.swing.JLabel datoStock;
    public javax.swing.JTextField datoTarjeta;
    public javax.swing.JTextField datoTelefono;
    public javax.swing.JTextPane descripcion;
    public javax.swing.JScrollPane descripcion1;
    public javax.swing.JLabel disco;
    public javax.swing.JComboBox<String> discoBox;
    public javax.swing.JButton eliminaTodoCarro;
    public javax.swing.JButton eliminarArticulo;
    public javax.swing.JLabel fechaPedidoInf;
    private javax.swing.JLabel fotoInicio;
    public javax.swing.JLabel fuente;
    public javax.swing.JComboBox<String> fuenteBox;
    public javax.swing.JLabel grafica;
    public javax.swing.JComboBox<String> graficaBox;
    public javax.swing.JLabel imgProducto;
    private javax.swing.JPanel infoPanelAnadir1;
    private javax.swing.JPanel infoPanelAnadir3;
    public javax.swing.JButton insertarCesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel labelDeshacer;
    public javax.swing.JList<String> listaCompras;
    public javax.swing.JList<String> listaInfoPedido;
    public javax.swing.JList<String> listaPedidos;
    public javax.swing.JList<String> listaProductos;
    public javax.swing.JLabel monitor;
    public javax.swing.JButton montaYcompra;
    public javax.swing.JButton montaYguarda;
    public javax.swing.JLabel nPedidoInfo;
    public javax.swing.JLabel nombreAtributo1;
    public javax.swing.JLabel nombreAtributo2;
    public javax.swing.JLabel nombreAtributo3;
    public javax.swing.JLabel nombreCliente;
    public javax.swing.JLabel nombrePerfil;
    public javax.swing.JPasswordField nuevaPass;
    public javax.swing.JTextField nuevoEmail;
    public javax.swing.JPanel panelArticulo;
    public javax.swing.JPanel panelCarro;
    public javax.swing.JPanel panelCompras;
    public javax.swing.JPanel panelElegirProducto;
    public javax.swing.JPanel panelInfoPedido;
    public javax.swing.JPanel panelInicio;
    public javax.swing.JPanel panelMonta;
    public javax.swing.JPanel panelPerfil;
    public javax.swing.JPanel panelProducto;
    public javax.swing.JLabel pctorre;
    public javax.swing.JLabel placaBase;
    public javax.swing.JComboBox<String> placaBox;
    public javax.swing.JLabel portatil;
    public javax.swing.JLabel precio;
    public javax.swing.JLabel precioCarro;
    public javax.swing.JLabel precioTotalPc;
    public javax.swing.JLabel productoSeleccionado;
    public javax.swing.JButton puntuacion1;
    public javax.swing.JButton puntuacion2;
    public javax.swing.JButton puntuacion3;
    public javax.swing.JButton puntuacion4;
    public javax.swing.JButton puntuacion5;
    public javax.swing.JLabel ram;
    public javax.swing.JComboBox<String> ramBox;
    public javax.swing.JLabel raton;
    public javax.swing.JComboBox<String> ratonBox;
    public javax.swing.JPasswordField repitePass;
    public javax.swing.JLabel teclado;
    public javax.swing.JComboBox<String> tecladoBox;
    public javax.swing.JTextField textoBusqueda;
    // End of variables declaration//GEN-END:variables
}
