/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Alberto
 */
public class InicioEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InicioEmpleado
     */
    public InicioEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        imagenUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        barraBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnCompras = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JLabel();
        btnAnnadir = new javax.swing.JLabel();
        btnEditarArticulo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        panelInicioInfo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datoNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datoApellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        datoEmail = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        datoDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        datoTelefono = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datoDni = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idTienda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombreTienda = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        direccionTienda = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        codTienda = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ciudadTienda = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        provinciaTienda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        panelEditarPerfil = new javax.swing.JPanel();
        infoPanelProductos = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        panelCompras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedidos = new javax.swing.JList<>();
        infoPanelCompras = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        panelAnadir = new javax.swing.JPanel();
        infoPanelAnadir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        panelElegirProducto = new javax.swing.JPanel();
        infoPanelAnadir1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        panelEditarProducto = new javax.swing.JPanel();
        infoPanelAnadir2 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreUsuario.setText("jLabel2");
        jPanel2.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, 440, -1));

        imagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(imagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 41));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 21, -1, 40));

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AREA DE PERSONAL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        panelLateral.setBackground(new java.awt.Color(153, 153, 153));
        panelLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 10));

        barraBusqueda.setBackground(new java.awt.Color(51, 51, 51));
        barraBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setBorder(null);
        panelLateral.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 30));

        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        panelLateral.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, -1));

        btnCompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Carrito.png"))); // NOI18N
        btnCompras.setText(" Ver compras");
        panelLateral.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 60));

        btnPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        panelLateral.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 60));

        btnEditarPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnEditarPerfil.setText(" Editar perfil");
        btnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseClicked(evt);
            }
        });
        panelLateral.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 230, 70));

        btnAnnadir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAnnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnadir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAnnadir.setText(" Añadir artículo");
        panelLateral.add(btnAnnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 60));

        btnEditarArticulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarArticulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustes.png"))); // NOI18N
        btnEditarArticulo.setText(" Editar artículo");
        panelLateral.add(btnEditarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 70));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 382, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 250, -1));

        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSesion.png"))); // NOI18N
        btnCerrar.setText("Cerrar sesion");
        btnCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelLateral.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 220, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BUSQUEDA:");
        panelLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, -1));

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 760));

        panelInicio.setBackground(new java.awt.Color(51, 51, 51));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicioInfo.setBackground(new java.awt.Color(51, 51, 51));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EL REY DEL PC");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATOS USUARIO");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 186, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 62, 119, -1));

        datoNombre.setForeground(new java.awt.Color(153, 153, 153));
        datoNombre.setText("jLabel7");
        jPanel8.add(datoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 88, 119, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APELLIDO");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, -1, -1));

        datoApellido.setForeground(new java.awt.Color(153, 153, 153));
        datoApellido.setText("jLabel9");
        jPanel8.add(datoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 146, 119, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMAIL");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 178, -1, -1));

        datoEmail.setForeground(new java.awt.Color(153, 153, 153));
        datoEmail.setText("jLabel9");
        jPanel8.add(datoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 204, 119, -1));

        direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setText("DIRECCION");
        jPanel8.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 236, -1, -1));

        datoDireccion.setForeground(new java.awt.Color(153, 153, 153));
        datoDireccion.setText("jLabel11");
        jPanel8.add(datoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 262, 119, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TELEFONO");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 294, -1, -1));

        datoTelefono.setForeground(new java.awt.Color(153, 153, 153));
        datoTelefono.setText("jLabel13");
        jPanel8.add(datoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 320, 119, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 352, -1, -1));

        datoDni.setForeground(new java.awt.Color(153, 153, 153));
        datoDni.setText("jLabel10");
        jPanel8.add(datoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 378, 119, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATOS TIENDA");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 10, 155, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 62, -1, -1));

        idTienda.setForeground(new java.awt.Color(153, 153, 153));
        idTienda.setText("jLabel14");
        jPanel8.add(idTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 88, 155, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOMBRE");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 120, -1, -1));

        nombreTienda.setForeground(new java.awt.Color(153, 153, 153));
        nombreTienda.setText("jLabel16");
        jPanel8.add(nombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 146, 155, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DIRECCION");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 178, -1, -1));

        direccionTienda.setForeground(new java.awt.Color(153, 153, 153));
        direccionTienda.setText("jLabel18");
        jPanel8.add(direccionTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 204, 155, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("COD. POSTAL");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 236, -1, -1));

        codTienda.setForeground(new java.awt.Color(153, 153, 153));
        codTienda.setText("jLabel20");
        jPanel8.add(codTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 262, 155, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CIUDAD");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 294, -1, -1));

        ciudadTienda.setForeground(new java.awt.Color(153, 153, 153));
        ciudadTienda.setText("jLabel22");
        jPanel8.add(ciudadTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 320, 155, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PROVINCIA");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 352, -1, -1));

        provinciaTienda.setForeground(new java.awt.Color(153, 153, 153));
        provinciaTienda.setText("jLabel14");
        jPanel8.add(provinciaTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 378, 155, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sevicioTecnico.png"))); // NOI18N

        javax.swing.GroupLayout panelInicioInfoLayout = new javax.swing.GroupLayout(panelInicioInfo);
        panelInicioInfo.setLayout(panelInicioInfoLayout);
        panelInicioInfoLayout.setHorizontalGroup(
            panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioInfoLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInicioInfoLayout.setVerticalGroup(
            panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelInicio.add(panelInicioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 680));

        panelEditarPerfil.setBackground(new java.awt.Color(51, 51, 51));
        panelEditarPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelProductos.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Edite su perfil desde esta interfaz");
        infoPanelProductos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));
        infoPanelProductos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelProductos.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Editar perfil");
        infoPanelProductos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelEditarPerfil.add(infoPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        getContentPane().add(panelEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelCompras.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPedidos.setBackground(new java.awt.Color(51, 51, 51));
        listaPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaPedidos.setForeground(new java.awt.Color(255, 255, 255));
        listaPedidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPedidos);

        panelCompras.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 820, 450));

        infoPanelCompras.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Pedidos realizados por los clientes en nuestra aplicación");
        infoPanelCompras.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));
        infoPanelCompras.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelCompras.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Resumen pedidos");
        infoPanelCompras.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelCompras.add(infoPanelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        getContentPane().add(panelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelAnadir.setBackground(new java.awt.Color(51, 51, 51));
        panelAnadir.setPreferredSize(new java.awt.Dimension(960, 620));
        panelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nuevo producto");
        infoPanelAnadir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));
        infoPanelAnadir.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Añada un nuevo artículo al catálogo");
        infoPanelAnadir.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelAnadir.add(infoPanelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        getContentPane().add(panelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelElegirProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelElegirProducto.setPreferredSize(new java.awt.Dimension(960, 620));
        panelElegirProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir1.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Catálogo de productos");
        infoPanelAnadir1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));
        infoPanelAnadir1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 71));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Elija el producto a editar");
        infoPanelAnadir1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelElegirProducto.add(infoPanelAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        listaProductos.setBackground(new java.awt.Color(51, 51, 51));
        listaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaProductos.setForeground(new java.awt.Color(255, 255, 255));
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaProductos);

        panelElegirProducto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 800, 450));

        getContentPane().add(panelElegirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelEditarProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelEditarProducto.setPreferredSize(new java.awt.Dimension(960, 620));
        panelEditarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir2.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Editar producto");
        infoPanelAnadir2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));
        infoPanelAnadir2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("Elija y modifique los campos a editar");
        infoPanelAnadir2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelEditarProducto.add(infoPanelAnadir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        getContentPane().add(panelEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseClicked
        // TODO add your handling code here:
        //panelInicio.setVisible(false);
        //panelArticulo.setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField barraBusqueda;
    public javax.swing.JLabel btnAnnadir;
    public javax.swing.JLabel btnBuscar;
    public javax.swing.JLabel btnCerrar;
    public javax.swing.JLabel btnCompras;
    public javax.swing.JLabel btnEditarArticulo;
    public javax.swing.JLabel btnEditarPerfil;
    public javax.swing.JLabel btnPerfil;
    public javax.swing.JLabel ciudadTienda;
    public javax.swing.JLabel codTienda;
    public javax.swing.JLabel datoApellido;
    public javax.swing.JLabel datoDireccion;
    public javax.swing.JLabel datoDni;
    public javax.swing.JLabel datoEmail;
    public javax.swing.JLabel datoNombre;
    public javax.swing.JLabel datoTelefono;
    private javax.swing.JLabel direccion;
    public javax.swing.JLabel direccionTienda;
    public javax.swing.JLabel idTienda;
    public javax.swing.JLabel imagenUsuario;
    private javax.swing.JPanel infoPanelAnadir;
    private javax.swing.JPanel infoPanelAnadir1;
    private javax.swing.JPanel infoPanelAnadir2;
    private javax.swing.JPanel infoPanelCompras;
    private javax.swing.JPanel infoPanelProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JList<String> listaPedidos;
    public javax.swing.JList<String> listaProductos;
    public javax.swing.JLabel nombreTienda;
    public javax.swing.JLabel nombreUsuario;
    public javax.swing.JPanel panelAnadir;
    public javax.swing.JPanel panelCompras;
    public javax.swing.JPanel panelEditarPerfil;
    public javax.swing.JPanel panelEditarProducto;
    public javax.swing.JPanel panelElegirProducto;
    public javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelInicioInfo;
    private javax.swing.JPanel panelLateral;
    public javax.swing.JLabel provinciaTienda;
    // End of variables declaration//GEN-END:variables
}
