/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Alberto
 */
public class InicioEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InicioEmpleado
     */
    public InicioEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        imagenUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        barraBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnCompras = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JLabel();
        btnAnnadir = new javax.swing.JLabel();
        btnEditarArticulo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        panelInicioInfo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datoNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datoApellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        datoEmail = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        datoDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        datoTelefono = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datoDni = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idTienda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombreTienda = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        direccionTienda = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        codTienda = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ciudadTienda = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        provinciaTienda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        panelEditarPerfil = new javax.swing.JPanel();
        infoPanelProductos = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tituloUsuarioId = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        direccion1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nombreEdit = new javax.swing.JTextField();
        apellidoEdit = new javax.swing.JTextField();
        telefonoEdit = new javax.swing.JTextField();
        direccionEdit = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnEditarDatos = new javax.swing.JButton();
        passActualEdit = new javax.swing.JPasswordField();
        passNuevaEdit = new javax.swing.JPasswordField();
        passRepitaEdit = new javax.swing.JPasswordField();
        panelCompras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedidos = new javax.swing.JList<>();
        infoPanelCompras = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        panelAnadir = new javax.swing.JPanel();
        infoPanelAnadir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tipoArticuloAnadir = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        codRefLabel = new javax.swing.JLabel();
        codRefAnadir = new javax.swing.JTextField();
        modeloLabel = new javax.swing.JLabel();
        modeloAnadir = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripcionAnadir = new javax.swing.JTextPane();
        jLabel39 = new javax.swing.JLabel();
        stockAnadir = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        precioAnadir = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        rutaImagenAnadir = new javax.swing.JTextField();
        atributo1Label = new javax.swing.JLabel();
        atributo1Anadir = new javax.swing.JTextField();
        atributo2Label = new javax.swing.JLabel();
        atributo2Anadir = new javax.swing.JTextField();
        atributo3Label = new javax.swing.JLabel();
        atributo3Anadir = new javax.swing.JTextField();
        btnAnadirNuevoArticulo = new javax.swing.JButton();
        panelElegirProducto = new javax.swing.JPanel();
        infoPanelAnadir1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        panelEditarProducto = new javax.swing.JPanel();
        infoPanelAnadir2 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        imgProductoEdit = new javax.swing.JLabel();
        nada = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        modeloEdit = new javax.swing.JTextField();
        precioEdit = new javax.swing.JTextField();
        stockEdit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionEdit = new javax.swing.JTextArea();
        btnEditarProducto = new javax.swing.JButton();
        btnBorrarProducto = new javax.swing.JButton();
        idProductoEdit = new javax.swing.JLabel();
        panelInfoPedido = new javax.swing.JPanel();
        infoPanelAnadir3 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaInfoPedido = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        nPedidoInfo = new javax.swing.JLabel();
        correoInfoPedido = new javax.swing.JLabel();

        jLabel35.setText("jLabel35");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreUsuario.setText("jLabel2");
        jPanel2.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, 440, -1));

        imagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(imagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 41));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 21, -1, 40));

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AREA DE PERSONAL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        panelLateral.setBackground(new java.awt.Color(153, 153, 153));
        panelLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 10));

        barraBusqueda.setBackground(new java.awt.Color(51, 51, 51));
        barraBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barraBusqueda.setBorder(null);
        barraBusqueda.setCaretColor(new java.awt.Color(255, 255, 255));
        panelLateral.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 40));

        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setPreferredSize(new java.awt.Dimension(32, 32));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        panelLateral.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 50, 40));

        btnCompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Carrito.png"))); // NOI18N
        btnCompras.setText(" Ver compras");
        panelLateral.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 60));

        btnPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        panelLateral.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 60));

        btnEditarPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnEditarPerfil.setText(" Editar perfil");
        btnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseClicked(evt);
            }
        });
        panelLateral.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 230, 70));

        btnAnnadir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAnnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnadir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAnnadir.setText(" Añadir artículo");
        panelLateral.add(btnAnnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 60));

        btnEditarArticulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarArticulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustes.png"))); // NOI18N
        btnEditarArticulo.setText(" Editar artículo");
        panelLateral.add(btnEditarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 70));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 382, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        panelLateral.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 250, -1));

        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSesion.png"))); // NOI18N
        btnCerrar.setText("Cerrar sesion");
        btnCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelLateral.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 220, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BUSQUEDA:");
        panelLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 760));

        panelInicio.setBackground(new java.awt.Color(51, 51, 51));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicioInfo.setBackground(new java.awt.Color(51, 51, 51));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EL REY DEL PC");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATOS USUARIO");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 186, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 62, 119, -1));

        datoNombre.setForeground(new java.awt.Color(153, 153, 153));
        datoNombre.setText("jLabel7");
        jPanel8.add(datoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 88, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APELLIDO");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, -1, -1));

        datoApellido.setForeground(new java.awt.Color(153, 153, 153));
        datoApellido.setText("jLabel9");
        jPanel8.add(datoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 146, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMAIL");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 178, -1, -1));

        datoEmail.setForeground(new java.awt.Color(153, 153, 153));
        datoEmail.setText("jLabel9");
        jPanel8.add(datoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 204, 220, -1));

        direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setText("DIRECCION");
        jPanel8.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 236, -1, -1));

        datoDireccion.setForeground(new java.awt.Color(153, 153, 153));
        datoDireccion.setText("jLabel11");
        jPanel8.add(datoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 262, 220, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TELEFONO");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 294, -1, -1));

        datoTelefono.setForeground(new java.awt.Color(153, 153, 153));
        datoTelefono.setText("jLabel13");
        jPanel8.add(datoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 320, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 352, -1, -1));

        datoDni.setForeground(new java.awt.Color(153, 153, 153));
        datoDni.setText("jLabel10");
        jPanel8.add(datoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 378, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATOS TIENDA");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 10, 155, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 62, -1, -1));

        idTienda.setForeground(new java.awt.Color(153, 153, 153));
        idTienda.setText("jLabel14");
        jPanel8.add(idTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 88, 210, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOMBRE");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 120, -1, -1));

        nombreTienda.setForeground(new java.awt.Color(153, 153, 153));
        nombreTienda.setText("jLabel16");
        jPanel8.add(nombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 146, 210, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DIRECCION");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 178, -1, -1));

        direccionTienda.setForeground(new java.awt.Color(153, 153, 153));
        direccionTienda.setText("jLabel18");
        jPanel8.add(direccionTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 204, 210, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("COD. POSTAL");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 236, -1, -1));

        codTienda.setForeground(new java.awt.Color(153, 153, 153));
        codTienda.setText("jLabel20");
        jPanel8.add(codTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 262, 210, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CIUDAD");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 294, -1, -1));

        ciudadTienda.setForeground(new java.awt.Color(153, 153, 153));
        ciudadTienda.setText("jLabel22");
        jPanel8.add(ciudadTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 320, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PROVINCIA");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 352, -1, -1));

        provinciaTienda.setForeground(new java.awt.Color(153, 153, 153));
        provinciaTienda.setText("jLabel14");
        jPanel8.add(provinciaTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 378, 210, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sevicioTecnico.png"))); // NOI18N

        javax.swing.GroupLayout panelInicioInfoLayout = new javax.swing.GroupLayout(panelInicioInfo);
        panelInicioInfo.setLayout(panelInicioInfoLayout);
        panelInicioInfoLayout.setHorizontalGroup(
            panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioInfoLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInicioInfoLayout.setVerticalGroup(
            panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelInicioInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelInicio.add(panelInicioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 680));

        panelEditarPerfil.setBackground(new java.awt.Color(51, 51, 51));
        panelEditarPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelProductos.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Edite su perfil desde esta interfaz");
        infoPanelProductos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));
        infoPanelProductos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelProductos.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Editar perfil");
        infoPanelProductos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelEditarPerfil.add(infoPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        tituloUsuarioId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tituloUsuarioId.setForeground(new java.awt.Color(255, 255, 255));
        tituloUsuarioId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloUsuarioId.setText("USUARIO ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(tituloUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloUsuarioId, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEditarPerfil.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 80));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NOMBRE");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("APELLIDO");

        direccion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        direccion1.setForeground(new java.awt.Color(255, 255, 255));
        direccion1.setText("DIRECCION");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("TELEFONO");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Contraseña actual");

        nombreEdit.setText("jTextField1");

        apellidoEdit.setText("jTextField1");
        apellidoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoEditActionPerformed(evt);
            }
        });

        telefonoEdit.setText("jTextField3");

        direccionEdit.setText("jTextField4");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nueva contraseña");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Repita contraseña");

        btnEditarDatos.setText("Editar");
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });

        passActualEdit.setText("jPasswordField1");

        passNuevaEdit.setText("jPasswordField2");

        passRepitaEdit.setText("jPasswordField3");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombreEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(apellidoEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonoEdit, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel22)
                            .addComponent(direccion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passNuevaEdit)
                            .addComponent(passActualEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(passRepitaEdit))
                        .addGap(113, 113, 113)
                        .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(nombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(telefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(direccion1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passRepitaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(passActualEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passNuevaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarDatos)))
                .addContainerGap())
        );

        panelEditarPerfil.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 720, 470));

        getContentPane().add(panelEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelCompras.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPedidos.setBackground(new java.awt.Color(51, 51, 51));
        listaPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaPedidos.setForeground(new java.awt.Color(255, 255, 255));
        listaPedidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPedidos);

        panelCompras.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 820, 450));

        infoPanelCompras.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Pedidos realizados por los clientes en nuestra aplicación");
        infoPanelCompras.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));
        infoPanelCompras.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelCompras.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Resumen pedidos");
        infoPanelCompras.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelCompras.add(infoPanelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        getContentPane().add(panelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelAnadir.setBackground(new java.awt.Color(51, 51, 51));
        panelAnadir.setPreferredSize(new java.awt.Dimension(960, 620));
        panelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nuevo producto");
        infoPanelAnadir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));
        infoPanelAnadir.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Añada un nuevo artículo al catálogo");
        infoPanelAnadir.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelAnadir.add(infoPanelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        tipoArticuloAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArticuloAnadirActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("TIPO: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(tipoArticuloAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoArticuloAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelAnadir.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 60));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        codRefLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        codRefLabel.setForeground(new java.awt.Color(255, 255, 255));
        codRefLabel.setText("Codigo referencia");

        codRefAnadir.setEditable(false);

        modeloLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        modeloLabel.setForeground(new java.awt.Color(255, 255, 255));
        modeloLabel.setText("Modelo");

        modeloAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloAnadirActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Descripcion");

        descripcionAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(descripcionAnadir);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Stock");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Precio");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Nombre imagen");

        atributo1Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        atributo1Label.setForeground(new java.awt.Color(255, 255, 255));
        atributo1Label.setVisible(false);
        atributo1Label.setText("*atributo 1*");

        atributo1Anadir.setVisible(false);
        atributo1Anadir.setText("nadaDeNada");

        atributo2Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        atributo2Label.setForeground(new java.awt.Color(255, 255, 255));
        atributo2Label.setVisible(false);
        atributo2Label.setText("*atributo 2*");

        atributo2Anadir.setVisible(false);
        atributo2Anadir.setText("nadaDeNada");

        atributo3Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        atributo3Label.setForeground(new java.awt.Color(255, 255, 255));
        atributo3Label.setVisible(false);
        atributo3Label.setText("*atributo 3*");

        atributo3Anadir.setVisible(false);
        atributo3Anadir.setText("nadaDeNada");

        btnAnadirNuevoArticulo.setText("Añadir artículo");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadirNuevoArticulo))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel38)
                                .addComponent(modeloLabel)
                                .addComponent(codRefLabel)
                                .addComponent(modeloAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(codRefAnadir))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel39)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(stockAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(precioAnadir)
                            .addComponent(rutaImagenAnadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atributo1Label)
                            .addComponent(atributo2Label)
                            .addComponent(atributo3Label)
                            .addComponent(atributo1Anadir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(atributo2Anadir)
                            .addComponent(atributo3Anadir))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codRefLabel)
                    .addComponent(jLabel39)
                    .addComponent(atributo1Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codRefAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atributo1Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloLabel)
                    .addComponent(jLabel44)
                    .addComponent(atributo2Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atributo2Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel45)
                    .addComponent(atributo3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rutaImagenAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(atributo3Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnAnadirNuevoArticulo)
                .addGap(34, 34, 34))
        );

        panelAnadir.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 910, 430));

        getContentPane().add(panelAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelElegirProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelElegirProducto.setPreferredSize(new java.awt.Dimension(960, 620));
        panelElegirProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir1.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Catálogo de productos");
        infoPanelAnadir1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));
        infoPanelAnadir1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 71));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Elija el producto a editar");
        infoPanelAnadir1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelElegirProducto.add(infoPanelAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        listaProductos.setBackground(new java.awt.Color(51, 51, 51));
        listaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaProductos.setForeground(new java.awt.Color(255, 255, 255));
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaProductos);

        panelElegirProducto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 800, 450));

        getContentPane().add(panelElegirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelEditarProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelEditarProducto.setPreferredSize(new java.awt.Dimension(960, 620));
        panelEditarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir2.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Editar producto");
        infoPanelAnadir2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));
        infoPanelAnadir2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 71));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("Elija y modifique los campos a editar");
        infoPanelAnadir2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelEditarProducto.add(infoPanelAnadir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        imgProductoEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgProductoEdit.setText("VISTA PREVIA");
        panelEditarProducto.add(imgProductoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 280));

        nada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nada.setForeground(new java.awt.Color(255, 255, 255));
        nada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nada.setText("PRODUCTO ID -");
        panelEditarProducto.add(nada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 80));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MODELO");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("STOCK");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("PRECIO");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("DESCRIPCION");

        modeloEdit.setText("jTextField1");
        modeloEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloEditActionPerformed(evt);
            }
        });

        precioEdit.setText("jTextField2");
        precioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioEditActionPerformed(evt);
            }
        });

        stockEdit.setText("jTextField3");

        descripcionEdit.setColumns(20);
        descripcionEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descripcionEdit.setLineWrap(true);
        descripcionEdit.setRows(5);
        jScrollPane3.setViewportView(descripcionEdit);

        btnEditarProducto.setText("Editar");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });

        btnBorrarProducto.setText("Borrar");
        btnBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(modeloEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32)
                            .addComponent(jLabel26)
                            .addComponent(precioEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(stockEdit))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(336, 336, 336))
                            .addComponent(jScrollPane3))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarProducto)
                    .addComponent(btnBorrarProducto))
                .addGap(25, 25, 25))
        );

        panelEditarProducto.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 520, 400));

        idProductoEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idProductoEdit.setForeground(new java.awt.Color(255, 255, 255));
        idProductoEdit.setText("3");
        panelEditarProducto.add(idProductoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, 80));

        getContentPane().add(panelEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        panelInfoPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelInfoPedido.setPreferredSize(new java.awt.Dimension(960, 620));
        panelInfoPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanelAnadir3.setBackground(new java.awt.Color(51, 51, 51));
        infoPanelAnadir3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Resumen pedido");
        infoPanelAnadir3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));
        infoPanelAnadir3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 10));

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPanelAnadir3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 71));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Información acerca de un pedido");
        infoPanelAnadir3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 420, 70));

        panelInfoPedido.add(infoPanelAnadir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        listaInfoPedido.setBackground(new java.awt.Color(51, 51, 51));
        listaInfoPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaInfoPedido.setForeground(new java.awt.Color(255, 255, 255));
        listaInfoPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaInfoPedido);

        panelInfoPedido.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 800, 420));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nº PEDIDO - ");

        nPedidoInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nPedidoInfo.setForeground(new java.awt.Color(255, 255, 255));
        nPedidoInfo.setText("ID PEDIDO");

        correoInfoPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        correoInfoPedido.setForeground(new java.awt.Color(255, 255, 255));
        correoInfoPedido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        correoInfoPedido.setText("email");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nPedidoInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(correoInfoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(nPedidoInfo)
                    .addComponent(correoInfoPedido))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelInfoPedido.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 70));

        getContentPane().add(panelInfoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 960, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseClicked
        // TODO add your handling code here:
        //panelInicio.setVisible(false);
        //panelArticulo.setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilMouseClicked

    private void apellidoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoEditActionPerformed

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void precioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioEditActionPerformed

    private void modeloEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloEditActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void tipoArticuloAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArticuloAnadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoArticuloAnadirActionPerformed

    private void modeloAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloAnadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloAnadirActionPerformed

    private void btnBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellidoEdit;
    public javax.swing.JTextField atributo1Anadir;
    public javax.swing.JLabel atributo1Label;
    public javax.swing.JTextField atributo2Anadir;
    public javax.swing.JLabel atributo2Label;
    public javax.swing.JTextField atributo3Anadir;
    public javax.swing.JLabel atributo3Label;
    public javax.swing.JTextField barraBusqueda;
    public javax.swing.JButton btnAnadirNuevoArticulo;
    public javax.swing.JLabel btnAnnadir;
    public javax.swing.JButton btnBorrarProducto;
    public javax.swing.JLabel btnBuscar;
    public javax.swing.JLabel btnCerrar;
    public javax.swing.JLabel btnCompras;
    public javax.swing.JLabel btnEditarArticulo;
    public javax.swing.JButton btnEditarDatos;
    public javax.swing.JLabel btnEditarPerfil;
    public javax.swing.JButton btnEditarProducto;
    public javax.swing.JLabel btnPerfil;
    public javax.swing.JLabel ciudadTienda;
    public javax.swing.JTextField codRefAnadir;
    public javax.swing.JLabel codRefLabel;
    public javax.swing.JLabel codTienda;
    public javax.swing.JLabel correoInfoPedido;
    public javax.swing.JLabel datoApellido;
    public javax.swing.JLabel datoDireccion;
    public javax.swing.JLabel datoDni;
    public javax.swing.JLabel datoEmail;
    public javax.swing.JLabel datoNombre;
    public javax.swing.JLabel datoTelefono;
    public javax.swing.JTextPane descripcionAnadir;
    public javax.swing.JTextArea descripcionEdit;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel direccion1;
    public javax.swing.JTextField direccionEdit;
    public javax.swing.JLabel direccionTienda;
    public javax.swing.JLabel idProductoEdit;
    public javax.swing.JLabel idTienda;
    public javax.swing.JLabel imagenUsuario;
    public javax.swing.JLabel imgProductoEdit;
    private javax.swing.JPanel infoPanelAnadir;
    private javax.swing.JPanel infoPanelAnadir1;
    private javax.swing.JPanel infoPanelAnadir2;
    private javax.swing.JPanel infoPanelAnadir3;
    private javax.swing.JPanel infoPanelCompras;
    private javax.swing.JPanel infoPanelProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JList<String> listaInfoPedido;
    public javax.swing.JList<String> listaPedidos;
    public javax.swing.JList<String> listaProductos;
    public javax.swing.JTextField modeloAnadir;
    public javax.swing.JTextField modeloEdit;
    public javax.swing.JLabel modeloLabel;
    public javax.swing.JLabel nPedidoInfo;
    private javax.swing.JLabel nada;
    public javax.swing.JTextField nombreEdit;
    public javax.swing.JLabel nombreTienda;
    public javax.swing.JLabel nombreUsuario;
    public javax.swing.JPanel panelAnadir;
    public javax.swing.JPanel panelCompras;
    public javax.swing.JPanel panelEditarPerfil;
    public javax.swing.JPanel panelEditarProducto;
    public javax.swing.JPanel panelElegirProducto;
    public javax.swing.JPanel panelInfoPedido;
    public javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelInicioInfo;
    private javax.swing.JPanel panelLateral;
    public javax.swing.JPasswordField passActualEdit;
    public javax.swing.JPasswordField passNuevaEdit;
    public javax.swing.JPasswordField passRepitaEdit;
    public javax.swing.JTextField precioAnadir;
    public javax.swing.JTextField precioEdit;
    public javax.swing.JLabel provinciaTienda;
    public javax.swing.JTextField rutaImagenAnadir;
    public javax.swing.JTextField stockAnadir;
    public javax.swing.JTextField stockEdit;
    public javax.swing.JTextField telefonoEdit;
    public javax.swing.JComboBox<String> tipoArticuloAnadir;
    public javax.swing.JLabel tituloUsuarioId;
    // End of variables declaration//GEN-END:variables
}
